version: "3.8"
services:
  app:
    build:
      context: "."
      args:
        # BASE: "corpusops/debian-32:bookworm"
        BASE: "corpusops/debian-32:trixie"
    volumes:
    - ./src:/app/src
    - ./setup.py:/app/setup.py
    - ./docker-entry.sh:/app/docker-entry.sh
